modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "smoothpickup"
version = "${version}-mc${minecraft_version}-neoforge"
displayName = "Smooth Pickup"
authors = "mineland"
description = '''
Smoothly picks up items on the inventory
'''
logoFile = "assets/smoothpickup/icon.png"

[[dependencies.smoothpickup]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.smoothpickup]]
modId = "minecraft"
type = "required"
versionRange = "${version_range_neo}"
ordering = "NONE"
side = "CLIENT"


[[mixins]]
config = "smoothpickup.mixins.json"

[[mixins]]
config = "smoothpickup.neo.mixins.json"

